# Generated by Django 4.0.4 on 2022-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_id', models.CharField(max_length=120)),
                ('avatar', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=100)),
                ('wordle', models.IntegerField(default=0)),
                ('papertoss', models.IntegerField(default=0)),
                ('points_spent', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(null=True)),
            ],
        ),
    ]
