# Generated by Django 4.0.4 on 2022-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points_spent',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='gambling_gains',
            field=models.IntegerField(default=0),
        ),
    ]
