# Generated by Django 4.0.4 on 2022-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_points_spent_user_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shwags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
