# Generated by Django 4.0.4 on 2022-04-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='currency',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shwags',
        ),
    ]
