# Generated by Django 4.0.4 on 2022-04-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_currency_user_total_score_remove_user_shwags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gambling_gains',
        ),
    ]
